### ISSUE TITLE
Will it support SimpleMembership?

### ISSUE THREAD

**Issue by victorwoo** [troygoode/MembershipStarterKit#28]
As SimpleMembershipProvider is based on ExtendedMembershipProvider, it needs to change something to support SimpleMembership in ASP.NET MVC 4.
Is there a plan to upgrade?

FYI:
http://weblogs.asp.net/jgalloway/archive/2012/08/29/simplemembership-membership-providers-universal-providers-and-the-new-asp-net-4-5-web-forms-and-asp-net-mvc-4-templates.aspx

**Comment by troygoode** [comment]
I've been thinking about this and I think I've decided _not_ to support SimpleMembership. I like SimpleMembership a lot (in theory - haven't used it yet) as it solves a lot of the problems that the core MvcMembership library (not the MvcMembership.Mvc controllers & views) was designed to solve: basic ASP.Net Membership was poorly designed, not testable, hard to integrate into IoC, etc. I believe there is room for another NuGet package that provides administration screens on top of SimpleMembership, but I don't think this is the right project for that since so much of what is done in here is to work around ASP.Net Membership's nonsense.

**Comment by victorwoo** [comment]
OK, thank you for your reply. Currently, there is few information (document, open source project, nuget packet, etc.) about SimpleMembership. If you've noticed something new about SimpleMembership, will you please inform me? Thank you.
victorwoo@gmail.com

**Comment by danmiser** [comment]
Same goes for the new Identity stuff in Mvc5. I like what Troy has done. I understand about the working around the original bad memebership stuff, but there is a definite need for an admin interface for the better providers.

**Comment by troygoode** [comment]
Agreed that someone needs to build this for ASP.NET Identity @danmiser, but this project isn't the one to do it (too much debt tied into the old Membership nonsense) and I'm not the guy to do it (no longer developing in .NET). Hopefully someone (maybe you!) will make it happen soon.

**Comment by danmiser** [comment]
:) Sorry to see you no longer in .NET. I will wait to see what MS comes up with in the near future, based on this comment by Hao:
http://stackoverflow.com/questions/18633040/get-all-role-names-in-asp-net-mvc5-identity-system?lq=1

If they don't add something, I'll take up the torch.
