### ISSUE TITLE
Two Nuget packages

### ISSUE THREAD

**Issue by bdelaney** [troygoode/MembershipStarterKit#32]
Why are there two Nuget packages. The nuspec files only indicate a different set of dependencies. Kind of confusing for an MVC noob to figure out.
Also, is this package supposed to be added to an MVC4 'Internet' template which already supports the new 'SimpleMembership' out of the box? Or do you expect it to be added to another template, like 'Basic?'

**Comment by troygoode** [comment]
One package "MvcMembership" is just a set of classes that make it easy to use and test the core Membership feature in .Net (not SimpleMembership). "MvcMembership.Mvc" contains the controllers & views that use the "MvcMembership" package to give you visual way of administering your site's members.

This package FAR pre-exists the SimpleMembership feature (MvcMembership has existed since before MVC 1.0 was released) so if SimpleMembership fits your needs feel free to use that instead. MvcMembership should work with any MVC4 template.
